name: CI?CD for Dockerized Flask App

on:
    push:
        nranches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/setup-python@v4
      with:
        python-version: "3,9"
        
    - name: Install dependencies
      run:
        python -mpipinstall --upgrade pip
        pip install flask
        pip install pytest

    - name: Run tests
      run:
        pytest

build-and-publsih:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Set up Docker Buildx
      uses: docker/seteup-builds-action@v2

    - name: Login to DockerHub
     uses: docker/login-action@v2
     with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with: 
        context: .
        file: ./DockerFile 
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest

    - name: Image digest
      run: echo ${{ steps.build-and-publish.outputs.digest }}
